travis:
  secure:
    BINSTAR_TOKEN: Ly/5Xs4Whq2jcYK9RzfMIsv2znopAHnv9yow/P0GI1kR/5zVbAH8rfp0n55aiYATXEcCA7CqBaEEwXPkXqaVdBjycqlQrlLyWtpjLiuVvKV90meXokBJTTsPq+0/owKrlYqQTkveu+vR2CHquigu3cRPJMT4uJlPplOgmzyGrMXN+3nTw/2BSrPFI7BVf2q2Pjf1GfFeAF/RXLR7cj6Stcy9mF2GsJwbU77lsw0fEX+uaXGqUWrnXqjGeI1OEx/6EjTni51fF32ywUdW0wjHuMzI5IhRzjztW0J0q/QSlFDvqTOMB7NboLOEf2CT1JhQlh9tHclydgfyfocb+8f/+W+AghqnXE+xN11ZauSg/wrg/JIXC9ByXMnm3EmUjA6y5gcfQNNrsQiWOCqL7KZVbN9IdsWirQPW2LMJgGeJ6qWTSxaovVtAAC0EfTmS8rHvdrBeuRNpaFkdunSLo+o6xZGMtDA0TVbqS4AphoOpbVqxjesUkPT1L8eTDsaa846kkFMvsZf8pE9j5JQi06iPB6UQ4pbzKCPyxWIGyvYN5QM8stZebuLs9YFWjX4WjvSQRVw11CIBxjT9JuuI9eTNElONgrMby3/9CiYKdciVh0jQ0EDH0NAMQmDXR+l53bLSmKXL6MzO0R19FJtnUe6wOWa6XgjqM54AeRZMmkPVw54=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
